# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:  # Added 'steps:' to define the steps in the pipeline
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'  # Consider using a more recent version of Node.js

- script: |
    npm install
    npm run build
    npm test  # Add this line if you want to run tests as well
  displayName: 'Install dependencies, build, and run tests'  # Add a display name for clarity

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Make sure to set the artifact path correctly
    ArtifactName: 'drop'
    publishLocation: 'Container'
