trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self  # Ensure the code is checked out

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Specify the Node.js version you want to use

- script: |
    cd NODEJS_PROJECTS/01_SimpleServer  # Change to the directory containing your package.json
    echo "Deleting package-lock.json if it exists..."
    rm -f package-lock.json   # Remove the package-lock.json file
    pwd                        # Print the working directory
    ls -ltr                    # List the files in the directory
    npm install                # Install dependencies
  displayName: 'Install dependencies'

- script: |
    cd NODEJS_PROJECTS/01_SimpleServer  # Change to the correct directory for artifact checking
    echo "Checking for artifacts:"
    ls -al                    # List all files to see if build artifacts are present
  displayName: 'Check for Artifacts After Install'
